import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";
import Footer from "@/components/Footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const BodyFont = Montserrat({subsets:['latin']});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${BodyFont.variable}`}
      >
        <div className="container">
          <NavBar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
